server:
  port: 8000

spring:
  application:
    name: api_gateway

  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/master/protocol/openid-connect/certs

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**,/auth/**,/api/admin/users/**,/users/**

        - id: salon-service
          uri: lb://SALON-SERVICE
          predicates:
            - Path=/salons/**,/api/salons/**,/api/admin/salons/**

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**

        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/categories/**

        - id: offering-service
          uri: lb://OFFERING-SERVICE
          predicates:
            - Path=/api/service-offering/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
